# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: khaniche <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/28 14:20:12 by khaniche          #+#    #+#              #
#    Updated: 2019/04/28 14:20:36 by khaniche         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc

NAME = fdf

FLAGS = -O2 -Wall -Wextra -Werror

LIBFT = libft

DIR_S = src

DIR_O = obj

HEADERS = inc

SOURCES = main.c draw.c ft_hooks.c projections.c set_project.c proj_var.c\
functions.c init.c

SRCS = $(addprefix $(DIR_S)/,$(SOURCES))

OBJS = $(addprefix $(DIR_O)/,$(SOURCES:.c=.o))

all: obj $(NAME)

$(NAME): $(OBJS)
		@make -C $(LIBFT)
		@$(CC) -g $(FLAGS) -L $(LIBFT) -lft -o $@ $^ -lmlx -framework OpenGL -framework AppKit

obj:
		@mkdir -p obj

$(DIR_O)/%.o: $(DIR_S)/%.c $(HEADERS)/$(NAME).h
		$(CC) -g $(FLAGS) -I $(HEADERS) -c -o $@ $<

clean:
		@rm -f $(OBJS)
		@make clean -C $(LIBFT)
		@rm -rf $(DIR_O)

fclean: clean
		@rm -f $(NAME)
		@make fclean -C $(LIBFT)

re: fclean all
